with self.assertRaises(${1:Exception}):
	${2}
